name: some_game
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flame: ^1.15.0
  flame_audio: ^1.3.3
  flame_tiled: ^1.18.4
  nes_ui: ^0.15.0
  go_router: ^13.1.0
  flame_riverpod: ^5.1.3
  flutter_riverpod: ^2.4.10
  google_fonts: ^4.0.4
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/tiles/
    - assets/audio/
    - assets/images/
    - assets/images/Terrain/
    - assets/images/Background/
    - assets/images/Items/Fruits/
    - assets/images/Traps/Saw/
    - assets/images/Items/Checkpoints/Checkpoint/
    - assets/images/Main Characters/Mask Dude/
    - assets/images/Main Characters/Ninja Frog/
    - assets/images/Main Characters/Pink Man/
    - assets/images/Main Characters/Virtual Guy/
    - assets/images/Main Characters/Pink Monster/
    - assets/images/HUD/
    - assets/images/numbers/
